---
- name: Deploy Brother Printer CTF Portal
  hosts: all
  become: yes
  # Define variables for easy custom use when final deployment is done
  vars:
    app_name: "brother-printer-ctf"
    app_user: "www-data"
    app_dir: "/var/www/{{ app_name }}"
    git_repo: "https://github.com/jeffaburke/brother-printer-ctf.git"
    
  tasks: # Update the package cache so there are no errors when trying to install packages
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-dev
          - apache2
          - libapache2-mod-wsgi-py3
          - git
          - ufw
          - build-essential
          - wget
          - curl
          - dpkg-dev
          - debhelper
          - devscripts
        state: present

    - name: Install vulnerable CUPS components from source
      apt:
        name:
          - cups=2.4.2-3+deb12u9
          - cups-client=2.4.2-3+deb12u9
          - cups-daemon=2.4.2-3+deb12u9
          - cups-common=2.4.2-3+deb12u9
          - cups-core-drivers=2.4.2-3+deb12u9
          - cups-ipp-utils=2.4.2-3+deb12u9
          - cups-ppdc=2.4.2-3+deb12u9
          - cups-server-common=2.4.2-3+deb12u9
          - libcups2=2.4.2-3+deb12u9
          - libcups2-dev=2.4.2-3+deb12u9
          - libcupscgi1=2.4.2-3+deb12u9
          - libcupsimage2=2.4.2-3+deb12u9
          - libcupsmime1=2.4.2-3+deb12u9
          - libcupsppdc1=2.4.2-3+deb12u9
          - printer-driver-all
          - cups-pdf
        state: present
        allow_downgrade: yes
        force: yes

    - name: Ensure build deps are installed for vulnerable CUPS components
      apt:
        name:
          - build-essential
          - autoconf
          - automake
          - libtool
          - pkg-config
          - libssl-dev
          - libcups2-dev
          - libxml2-dev
          - libdbus-1-dev
          - libpam0g-dev
          - git
          - wget
        state: present

    - name: Create build dir for vulnerable CUPS components
      file:
        path: /usr/local/src/cups-build
        state: directory
        mode: '0755'

    - name: Download libppd tarball
      get_url:
        url: "https://github.com/OpenPrinting/libppd/releases/download/2.1.0/libppd-2.1.0.tar.xz"
        dest: /usr/local/src/cups-build/libppd.tar.xz
        mode: '0644'

    - name: Extract libppd
      unarchive:
        src: /usr/local/src/cups-build/libppd.tar.xz
        dest: /usr/local/src/cups-build
        remote_src: yes

    - name: Build and install libppd
      shell: |
        set -e
        cd /usr/local/src/cups-build/libppd-*
        ./autogen.sh || true
        ./configure --prefix=/usr
        make -j"$(nproc)"
        make install
      args:
        warn: false

    - name: Download libcupsfilters tarball
      get_url:
        url: "https://github.com/OpenPrinting/libcupsfilters/archive/refs/tags/2.1b1.tar.gz"
        dest: /usr/local/src/cups-build/libcupsfilters.tar.gz
        mode: '0644'

    - name: Extract libcupsfilters
      unarchive:
        src: /usr/local/src/cups-build/libcupsfilters.tar.gz
        dest: /usr/local/src/cups-build
        remote_src: yes

    - name: Build and install libcupsfilters
      shell: |
        set -e
        cd /usr/local/src/cups-build/libcupsfilters-*
        ./autogen.sh || true
        ./configure --prefix=/usr
        make -j"$(nproc)"
        make install
      args:
        warn: false

    - name: Download cups-filters tarball
      get_url:
        url: "https://github.com/OpenPrinting/cups-filters/releases/download/2.0.1/cups-filters-2.0.1.tar.xz"
        dest: /usr/local/src/cups-build/cups-filters.tar.xz
        mode: '0644'

    - name: Extract cups-filters
      unarchive:
        src: /usr/local/src/cups-build/cups-filters.tar.xz
        dest: /usr/local/src/cups-build
        remote_src: yes

    - name: Build and install cups-filters
      shell: |
        set -e
        cd /usr/local/src/cups-build/cups-filters-*
        ./autogen.sh || true
        ./configure --prefix=/usr
        make -j"$(nproc)"
        make install
      args:
        warn: false

    - name: Download cups-browsed tarball
      get_url:
        url: "https://github.com/OpenPrinting/cups-browsed/archive/refs/tags/2.0.1.tar.gz"
        dest: /usr/local/src/cups-build/cups-browsed.tar.gz
        mode: '0644'

    - name: Extract cups-browsed
      unarchive:
        src: /usr/local/src/cups-build/cups-browsed.tar.gz
        dest: /usr/local/src/cups-build
        remote_src: yes

    - name: Build and install cups-browsed
      shell: |
        set -e
        cd /usr/local/src/cups-build/cups-browsed-*
        ./autogen.sh || true
        ./configure --prefix=/usr
        make -j"$(nproc)"
        make install
      args:
        warn: false

    - name: Pin vulnerable CUPS packages to prevent updates
      copy:
        content: |
          Package: cups cups-client cups-daemon cups-common cups-core-drivers cups-ipp-utils cups-ppdc cups-server-common libcups2 libcups2-dev libcupscgi1 libcupsimage2 libcupsmime1 libcupsppdc1
          Pin: version 2.4.2-3+deb12u9
          Pin-Priority: 1001
          
          Package: cups-browsed libcupsfilters libppd cups-filters
          Pin: release *
          Pin-Priority: 1001
        dest: /etc/apt/preferences.d/cups-vulnerable
        mode: '0644'

    - name: Enable and start CUPS service
      systemd:
        name: cups
        state: started
        enabled: yes

    - name: Ensure cups-browsed service is disabled (so it does not run during setup)
      systemd:
        name: cups-browsed
        state: stopped
        enabled: no
        masked: yes
      ignore_errors: yes

    - name: Enable Apache modules # Install the necessary Apache modules like WSGI so Apache can understand the python application
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - rewrite
        - wsgi
        - headers

    - name: Create application directory # Create the directory for the application with www-data as the owner
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Mark repo path as safe for git # This is needed so git can pull the repository as the root user
      git_config:
        name: "safe.directory"
        value: "{{ app_dir }}"

    - name: Clone repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        version: rce
        force: yes

    - name: Ensure requirements.txt exists # Check if the requirements.txt file exists if not next step will fail. Should be pulled from the repo
      stat:
        path: "{{ app_dir }}/requirements.txt"
      register: requirements_file

    - name: Fail if requirements.txt not found
      fail:
        msg: "requirements.txt not found in repository at {{ app_dir }}"
      when: not requirements_file.stat.exists

    - name: Create virtual environment for application # Create the virtual environment for the application so everything is self-contained and we don't have to worry about getting system python packages.
      command: "python3 -m venv {{ app_dir }}/venv"
      args:
        creates: "{{ app_dir }}/venv"

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"
        virtualenv_python: python3

    - name: Copy WSGI entry point from repository # Copy the WSGI entry point from the repository to the application directory
      copy:
        src: "{{ app_dir }}/wsgi-entry.py"
        dest: "{{ app_dir }}/{{ app_name }}.wsgi"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
        remote_src: yes

    - name: Copy Apache configuration from repository # Copy the Apache configuration from the repository to the application directory
      copy:
        src: "{{ app_dir }}/apache-config.conf"
        dest: "/etc/apache2/sites-available/{{ app_name }}.conf"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes

    - name: Enable the new site # Enable the new site so Apache can use it vs the default
      command: a2ensite {{ app_name }}.conf
      args:
        creates: "/etc/apache2/sites-enabled/{{ app_name }}.conf"

    - name: Disable default Apache site # Disable the default site so Apache can use the new one and not serve the default page.
      command: a2dissite 000-default.conf
      args:
        removes: "/etc/apache2/sites-enabled/000-default.conf"

    - name: Restart and enable Apache # Restart and enable Apache so it can use the new site and not the default one.
      systemd:
        name: apache2
        state: restarted
        enabled: yes

    - name: Enable UFW firewall # Enable the UFW firewall so we can block all traffic except SSH and HTTP. This will help simplify the attack and defense surface.
      ufw:
        state: enabled
        policy: deny

    - name: Allow SSH access
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow HTTP access
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Set proper ownership of application directory # Set the ownership of the application directory to the www-data user so the application can write to it.
      file:
        path: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes

    - name: Validate Apache configuration # Validate the Apache configuration so we can make sure it's correct. This is sort of a last check to make sure everything is working as expected.
      command: apache2ctl configtest
      register: apache_config_test
      changed_when: false
      failed_when: apache_config_test.rc != 0

    - name: Wait for Apache to be ready
      wait_for:
        port: 80
        timeout: 30

    - name: Display deployment information # Display the deployment information so we can see what's been deployed.
      debug:
        msg: |
          Brother Printer CTF Portal has been deployed!
          Access URL: http://{{ ansible_default_ipv4.address }}
          Application Directory: {{ app_dir }}
          Default Credentials: 1234567 / 1234567\
          
          The application is ready to use!
